version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=super_secret_key
